name: jimanna
description: 평화교회 아바드 청년모임

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  animated_text_kit: ^4.2.3
  json_annotation: ^4.11.0
  cloud_firestore: ^6.3.0
  cupertino_icons: ^1.0.9
  firebase_core: ^4.7.0
  flutter_riverpod: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^3.1.0
  just_audio: ^0.10.5
  qr_flutter: ^4.1.0
  riverpod_annotation: ^4.0.2
  simple_gradient_text: ^1.4.0
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.0
  flutter_gen: ^5.14.1
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3
  very_good_analysis: ^10.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/music/

  fonts:
    - family: DungGeunMo
      fonts:
        - asset: assets/fonts/DungGeunMo.woff

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml