name: jimanna
description: 평화교회 아바드 청년모임

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  cloud_firestore:
  flutter_riverpod:
  freezed:
  freezed_annotation:
  qr_flutter: ^4.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable:
  build_runner: ^2.4.5
  very_good_analysis:
  flutter_gen: ^5.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DungGeunMo
      fonts:
        - asset: assets/fonts/DungGeunMo.woff
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml