name: jimanna
description: 평화교회 아바드 청년모임

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  cloud_firestore:
  flutter_riverpod:
  riverpod_annotation:
  freezed:
  freezed_annotation:
  qr_flutter: ^4.1.0
  url_strategy: ^0.2.0
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable:
  build_runner:
  very_good_analysis:
  flutter_gen: ^5.3.2
  riverpod_generator:

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DungGeunMo
      fonts:
        - asset: assets/fonts/DungGeunMo.woff

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml