name: Web Deploy

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - run: flutter --version
      - run: |
          # 1. build flutter web 
          flutter config --enable-web
          flutter pub get
          flutter build web --release
      - run: |
          # 2. change path to [existed lib/main.dart path]/build/web
          cd ./build/web
          pwd
          git init
          git config --global user.email kms0644804@naver.com
          git config --global user.name boring-km
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/boring-km/jimanna.git 
          git checkout -b release_web
          git add --all
          git commit -m "update"
          git push origin release_web -f
